### ISSUE TITLE
Add problem description

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/HackerRank-in-Java#2]
Currently, the repo only contains solution's problems but are not descriptive. You can add a _README.md_ file describing the problem or solution (if possible) in detail.

**Comment by kapishmalik** [comment]
I am interested to contribute a few solutions.

**Comment by Kvaibhav01** [comment]
Go ahead @kapishmalik !

**Comment by Sanghamitra1234** [comment]
I will try to add a few descriptions.

**Comment by Kvaibhav01** [comment]
Awesome @Sanghamitra1234 !
